import type { GameItem, ItemCategory, ItemRarity } from '@/lib/items/types'

export const ITEM_CATEGORIES: ItemCategory[] = [
  'rifle',
  'machinegun',
  'sniper',
  'shotgun',
  'smg',
  'equipment',
  'melee',
  'support',
]

export const ITEM_RARITIES: ItemRarity[] = ['common', 'rare', 'epic', 'legendary']

export const GAME_ITEMS: GameItem[] = [
  {
    id: 'stearone-rifle',
    category: 'rifle',
    rarity: 'legendary',
    name: { vi: 'Stearone AR-X', en: 'Stearone AR-X' },
    typeLabel: { vi: 'Súng trường', en: 'Assault Rifle' },
    rarityLabel: { vi: 'Huyền thoại', en: 'Legendary' },
    acquisition: { vi: 'Galaxy Chronicle — Nhiệm vụ chính', en: 'Galaxy Chronicle — Main quest' },
    description: {
      vi: 'Súng trường năng lượng Stearone, bắn xuyên khiên năng lượng và tích tụ sát thương theo chuỗi.',
      en: 'A Stearone energy rifle that pierces shields and builds damage through sustained bursts.',
    },
    image: '/videos/Slider/582290225_798385386365728_2558834946497418310_n 3.png',
    accent: '#00cbff',
    power: { pve: 'SSS', pvp: 'SS', boss: 'SS' },
  },
  {
    id: 'nova-beam',
    category: 'sniper',
    rarity: 'epic',
    name: { vi: 'Nova Beam MK-II', en: 'Nova Beam MK-II' },
    typeLabel: { vi: 'Súng bắn tỉa', en: 'Sniper Rifle' },
    rarityLabel: { vi: 'Sử thi', en: 'Epic' },
    acquisition: { vi: 'Galaxy Chronicle — Rương tinh vân', en: 'Galaxy Chronicle — Nebula cache' },
    description: {
      vi: 'Tia sáng tập trung gây bùng nổ nhỏ khi trúng điểm yếu của mục tiêu.',
      en: 'A focused light beam that triggers small detonations on weak points.',
    },
    accent: '#c864fa',
    power: { pve: 'SS', pvp: 'SSS', boss: 'S' },
  },
  {
    id: 'plasma-smg',
    category: 'smg',
    rarity: 'rare',
    name: { vi: 'Plasma Veil SMG', en: 'Plasma Veil SMG' },
    typeLabel: { vi: 'Súng tiểu liên', en: 'SMG' },
    rarityLabel: { vi: 'Hiếm', en: 'Rare' },
    acquisition: { vi: 'Galaxy Chronicle — Chế tạo trạm', en: 'Galaxy Chronicle — Station crafting' },
    description: {
      vi: 'Tốc độ bắn cao, thích hợp cận chiến trong hành lang tàu vũ trụ.',
      en: 'High fire rate ideal for close quarters aboard starship corridors.',
    },
    accent: '#22c55e',
    power: { pve: 'A', pvp: 'SS', boss: 'A' },
  },
  {
    id: 'orbit-lmg',
    category: 'machinegun',
    rarity: 'epic',
    name: { vi: 'Orbit LMG-7', en: 'Orbit LMG-7' },
    typeLabel: { vi: 'Súng máy', en: 'Machine Gun' },
    rarityLabel: { vi: 'Sử thi', en: 'Epic' },
    acquisition: { vi: 'Galaxy Chronicle — Boss hạm đội', en: 'Galaxy Chronicle — Fleet boss' },
    description: {
      vi: 'Băng đạn lớn và lực đẩy mạnh, kiểm soát khu vực hiệu quả.',
      en: 'Large magazine and strong suppression for area control.',
    },
    accent: '#ff5740',
    power: { pve: 'SS', pvp: 'A', boss: 'SSS' },
  },
  {
    id: 'scrap-cannon',
    category: 'shotgun',
    rarity: 'epic',
    name: { vi: 'Scrap Cannon', en: 'Scrap Cannon' },
    typeLabel: { vi: 'Súng shotgun', en: 'Shotgun' },
    rarityLabel: { vi: 'Sử thi', en: 'Epic' },
    acquisition: { vi: 'The Junk Squad — Đống phế liệu', en: 'The Junk Squad — Scrap heap' },
    description: {
      vi: 'Ghép từ ống thép và lò xo cũ, tản đạn kim loại trong phạm vi ngắn.',
      en: 'Built from pipe and springs, scattering metal shards at close range.',
    },
    image:
      '/videos/Slider/gpt-image-2_A_gritty_post-apocalyptic_scene_from_the_game_Back_4_Blood_with_four_survivors_s-0.jpg',
    accent: '#ffbb00',
    power: { pve: 'SS', pvp: 'SS', boss: 'A' },
  },
  {
    id: 'wrench-hammer',
    category: 'melee',
    rarity: 'rare',
    name: { vi: 'Wrench Hammer', en: 'Wrench Hammer' },
    typeLabel: { vi: 'Cận chiến', en: 'Melee' },
    rarityLabel: { vi: 'Hiếm', en: 'Rare' },
    acquisition: { vi: 'The Junk Squad — Rèn tạm', en: 'The Junk Squad — Improvised forge' },
    description: {
      vi: 'Cờ lê khổng lồ gia cố thép, cho đòn choáng ngắn.',
      en: 'An oversized reinforced wrench that delivers brief stuns.',
    },
    accent: '#94a3b8',
    power: { pve: 'A', pvp: 'S', boss: 'B' },
  },
  {
    id: 'field-repair-kit',
    category: 'equipment',
    rarity: 'common',
    name: { vi: 'Field Repair Kit', en: 'Field Repair Kit' },
    typeLabel: { vi: 'Trang bị', en: 'Equipment' },
    rarityLabel: { vi: 'Thường', en: 'Common' },
    acquisition: { vi: 'The Junk Squad — Loot cơ bản', en: 'The Junk Squad — Basic loot' },
    description: {
      vi: 'Sửa nhanh giáp đồng đội và bổ sung lớp chắn tạm thời.',
      en: 'Quickly repairs ally armor and adds a temporary shield layer.',
    },
    accent: '#64748b',
    power: { pve: 'B', pvp: 'C', boss: 'B' },
  },
  {
    id: 'pulse-grenade',
    category: 'support',
    rarity: 'rare',
    name: { vi: 'Pulse Grenade', en: 'Pulse Grenade' },
    typeLabel: { vi: 'Hỗ trợ', en: 'Support' },
    rarityLabel: { vi: 'Hiếm', en: 'Rare' },
    acquisition: { vi: 'Galaxy Chronicle — Nhiệm vụ phụ', en: 'Galaxy Chronicle — Side mission' },
    description: {
      vi: 'Làm chậm kẻ địch trong vùng nổ và vô hiệu hóa drone gần đó.',
      en: 'Slows enemies in the blast radius and disables nearby drones.',
    },
    accent: '#38bdf8',
    power: { pve: 'S', pvp: 'A', boss: 'SS' },
  },
  {
    id: 'echo-carbine',
    category: 'rifle',
    rarity: 'rare',
    name: { vi: 'Echo Carbine', en: 'Echo Carbine' },
    typeLabel: { vi: 'Súng trường', en: 'Assault Rifle' },
    rarityLabel: { vi: 'Hiếm', en: 'Rare' },
    acquisition: { vi: 'Galaxy Chronicle — Chợ chợ đen', en: 'Galaxy Chronicle — Black market' },
    description: {
      vi: 'Bản sao dân sự của AR-X, ổn định và dễ kiểm soát hơn.',
      en: 'A civilian copy of the AR-X, stable and easier to control.',
    },
    accent: '#818cf8',
    power: { pve: 'A', pvp: 'A', boss: 'A' },
  },
  {
    id: 'rust-burst',
    category: 'smg',
    rarity: 'common',
    name: { vi: 'Rust Burst', en: 'Rust Burst' },
    typeLabel: { vi: 'Súng tiểu liên', en: 'SMG' },
    rarityLabel: { vi: 'Thường', en: 'Common' },
    acquisition: { vi: 'The Junk Squad — Khởi đầu', en: 'The Junk Squad — Starter loadout' },
    description: {
      vi: 'SMG tự chế, độ tin cậy thấp nhưng dễ tìm đạn.',
      en: 'A improvised SMG with low reliability but plentiful ammo.',
    },
    accent: '#a16207',
    power: { pve: 'C', pvp: 'B', boss: 'C' },
  },
  {
    id: 'guardian-shield',
    category: 'equipment',
    rarity: 'epic',
    name: { vi: 'Guardian Shield', en: 'Guardian Shield' },
    typeLabel: { vi: 'Trang bị', en: 'Equipment' },
    rarityLabel: { vi: 'Sử thi', en: 'Epic' },
    acquisition: { vi: 'Galaxy Chronicle — Phần thưởng hạm', en: 'Galaxy Chronicle — Ship reward' },
    description: {
      vi: 'Khiên năng lượng hấp thụ một phần sát thương hướng tới.',
      en: 'An energy shield that absorbs a portion of frontal damage.',
    },
    accent: '#2dd4bf',
    power: { pve: 'SS', pvp: 'S', boss: 'A' },
  },
  {
    id: 'salvage-launcher',
    category: 'support',
    rarity: 'common',
    name: { vi: 'Salvage Launcher', en: 'Salvage Launcher' },
    typeLabel: { vi: 'Hỗ trợ', en: 'Support' },
    rarityLabel: { vi: 'Thường', en: 'Common' },
    acquisition: { vi: 'The Junk Squad — Workshop', en: 'The Junk Squad — Workshop' },
    description: {
      vi: 'Bắn mồi kim loại gây nhiễu radar và thu hút zombie ngắn hạn.',
      en: 'Fires metal decoys that jam radar and briefly attract infected.',
    },
    accent: '#f97316',
    power: { pve: 'B', pvp: 'C', boss: 'B' },
  },
]
